<template>
  <div>
    <a-alert
        message="下一步计划安排"
        description="打造的专属前端组建库"
        type="success"
        show-icon
    />
    <br>
    <a-alert
        message="2024-9-1"
        description="解决生成基础的前端的table和表单文件"
        type="info"
        show-icon
    />
    <br>
    <a-alert
        message="2024-8-27"
        description="解决后端验证器代码生成"
        type="info"
        show-icon
    />
    <br>
    <a-alert
        message="2024-8-26"
        description="解决前端代码打包bug问题"
        type="info"
        show-icon
    />
    <br>
    <a-alert
        message="2024-8-28"
        description="控制器、逻辑层、模型层代码生成完毕"
        type="info"
        show-icon
    />
  </div>
</template>
<script lang="ts" setup>

</script>

